apiVersion: apps/v1
kind: Deployment
metadata:
  name: crazonhttpserver
  labels:
    app: crazonhttpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crazonhttpserver
  template:
    metadata:
      labels:
        app: crazonhttpserver
    spec:
      containers:
      - name: crazonhttpserver
        image: crazon/httpserver:v1.6
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
